[tool.poetry]
name = "ad-optimization"
version = "0.1.0"
description = ""
authors = ["Nikolas Schriefer <info@nikolasschriefer.de>"]

[tool.poetry.dependencies]
python = "^3.8"
flask = "^1.1.2"
zappa = "^0.52.0"
pandas = "^1.1.0"
scipy = "^1.5.2"
matplotlib = "^3.3.1"
sentry-sdk = {version = "^0.19.5", extras = ["flask"]}
flask-restx = "^0.2.0"
# facebook_business = "^8.0.2"

[tool.poetry.dev-dependencies]
python-dotenv = "^0.15.0"
flake8 = "^3.8.3"
coverage = "^5.1"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
